title: Liming Lu's Homepage
page-top-title: Limng Lu
top-section-bg-text: Attention is All You Need
home-subtitle: Liming Lu&ensp;|&ensp; B.S. @ Shanghai Jiao Tong University
copyright-text: '&copy; Liming Lu 2025-2026. All Rights Reserved.'
